# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: xenial
sudo: required
language: r
r_packages:
  - devtools
  - stringi
  - testthat
matrix:
  include:
  - os: linux
    r: release
  - os: linux
    r: oldrel
  - os: linux
    r: devel

warnings_are_errors: true
r_build_args: "--no-manual"
r_check_args: "--no-manual --as-cran"
