# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkPlagiarism_gplag_cpp_list_kernel2_test <- function(parses, h, sums) {
    .Call(`_SimilaR_checkPlagiarism_gplag_cpp_list_kernel2_test`, parses, h, sums)
}

generateDataFrame_one_rcpp <- function(matKernel2, functionNames) {
    .Call(`_SimilaR_generateDataFrame_one_rcpp`, matKernel2, functionNames)
}

generateDataFrame_one_both_rcpp <- function(matKernel2, functionNames) {
    .Call(`_SimilaR_generateDataFrame_one_both_rcpp`, matKernel2, functionNames)
}

